import hashlib
import json
from textwrap import dedent
from time import time
from uuid import uuid4

from flask import Flask
from flask import jsonify

class Blockchain(object):
    """
    It's a blockchain object implementation with all the POW features
    """


    def __init__(self):
        self.chain = []
        self.current_transactions = []

        #Create the genesis block with no predecessors
        self.new_block(previous_hash=1, proof = 100)

    def new_block(self, proof, previous_hash = None):
        """
        creating a new block and append it to the end of blockchain
        :param proof: <int> a key number generated by proof of work
        :param previous_hash: <str> Hash of previous block
        :return: <Blockchain> New Block
        """

        block ={
            'index': len(self.chain+1),
            'timestamp': time(),
            'transactions': self.current_transactions,
            'proof': proof,
            'previous_hash': previous_hash or self.hash(self.chain[-1]),
        }

        #reset transactions
        self.current_transactions = []
        self.chain.append(block)
        return block

    def new_transaction(self, sender, recipient, amount):
        """
        add a new transaction in temp and add it to new block later on
        :param sender: <str>
        :param recipient: <str>
        :param amount: <int>
        :return: <int>
        """

        self.current_transactions.append({
            'sender': sender,
            'recipient': recipient,
            'amount': amount
        })
        return self.last_block['index'] + 1


    @staticmethod
    def hash(block):
        """
        use this hash function to chain the blocks together
        :param block: <Blockchain>
        :return: <int>
        """

        block_string = json.dumps(block, sort_keys=True).encode()
        return hashlib.sha256(block_string).hexdigest()

    @property
    def last_block(self):
        """
        return the last block in the blockchain
        :return: <Blockchain>
        """
        return self.chain[-1]

    def proof_of_work(self, last_proof):
        """
        simple POF to find a hash result which has 4 leading zeros
        :param last_proof: <int>
        :return: <int>
        """
        proof = 0
        while self.valid_proof(last_proof, proof) is False:
            proof += 1

        return proof


    @staticmethod
    def valid_proof(last_proof, proof):
        """
        chech if we got a valid proof which can produce 4 leading zeros
        :param last_proof: <int>
        :param proof: <int>
        :return: <bool>
        """
        guess = f'{last_proof}{proof}'.encode()
        guess_hash = hashlib.sha256(guess).hexdigest()
        return guess_hash[:4] == "0000"

#create node
app = Flask(__name__)

node_identifier = str(uuid4()).replace('-','')

#create new blockchain
blockchain = Blockchain()

@app.route('/mine',methods=['GET'])
def mine():
    #mine a block
    pass

@app.route('transactions/new',method=['POST'])
def new_transaction():
    #add new transaction
    pass


@app.route('/chain',method=['GET'])
def full_chain():
    response = {
        'chain': blockchain.chain,
        'length': len(blockchain.chain),
    }
    return jsonify(response),200

if __name__ == '__main__':
    app.run(host='127.0.0.1',port = 5000)
